[package]
name = "granseal_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
granseal_engine = {path = "../granseal_engine"}
pollster = "0.2.5"
winit = "0.26.1"